version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: spelunq-rabbitmq
    ports:
      - "5672:5672"    # AMQP port
      - "15672:15672"  # Management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - spelunq-network

  # Optional: RabbitMQ queue initializer
  rabbitmq-init:
    image: rabbitmq:3-management
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
    volumes:
      - ./init-queues.sh:/init-queues.sh
    command: /bin/bash -c "chmod +x /init-queues.sh && /init-queues.sh"
    networks:
      - spelunq-network

volumes:
  rabbitmq_data:

networks:
  spelunq-network:
    driver: bridge
